### ISSUE TITLE
Night Vision

### ISSUE THREAD

**Issue by matthias1403** [idkjustgoogleit/esp32#1]
Hi,

I have already a similar doorbell and would like to "upgrade" it with night vision. Don't you need an IR shutter that the camera is able to capture IR? How is the night view if you keep the IR filter?

Thanks & Best regard, Matthias

**Comment by idkjustgoogleit** [comment]
Hi Matthias,

In the parts list I had added a fish eye lens camera which just works. That one doesn't have a certain filter, and at the same time during daylight the image is very good without color issues for my frontdoor usage. This could probably be different in other lighting.

However I'm not sure if the one I have is very sensitive to ir light, because the ir led ring I use appears to light up the person in front of the camera too much which I counteract with a different camera image setting for Night usage. Otherwise the image is unusable.

If I would redo, I would just do a few ir leds instead of a led ring with 12+ leds like I have now :) 

But I don't know (yet) how to make e.g. a model with just 2 it ir leds operating at 940nm wave length. Also to make those 2 leds to work on 5v instead of 12v would cutout the need of a step down converter.

Hope this gives some insight.

Good luck!
